#!/bin/sh

/usr/lib/cgi-bin/platstat | grep -v "META" > /tmp/platstat.html
/home/observer/PyDevel/Prosp/extras/cloudgraph.py > /dev/null 2>&1
scp /tmp/platstat.html /tmp/reducelog /tmp/clouds.png webpage@192.168.26.71:/var/www/platstat > /tmp/rplatstat.log

