#!/usr/bin/python

import cgi
import sys
import traceback

print('Content-Type: text/html\n\n')

try:
    import nobjedit

    form = cgi.FieldStorage()

    print(nobjedit.page(form))
except:
    print("There has been an error. Please cut and paste this error information")
    print("in an email to andrew@longtable.org.<p>\n<p>\n")
    e = traceback.format_exc()
    for line in e:
        print(cgi.escape(line) + '<p>').replace('\n', '<br>')
